services:
  db:
    image: postgres:15-alpine
    container_name: locadora-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: locadoradb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d locadoradb"]
      interval: 10s
      retries: 5

  backend:
    build: ./backend-javaspring
    container_name: locadora-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/locadoradb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_PROFILES_ACTIVE=prod
      - APPLICATION_SECURITY_JWT_SECRET_KEY=${JWT_SECRET}=
      - SERVER_SERVLET_CONTEXT_PATH=/api
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./app-quasar
    container_name: locadora-frontend

  gateway:
    image: nginx:alpine
    container_name: locadora-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend

  ngrok:
    image: ngrok/ngrok:latest
    container_name: locadora-ngrok
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    command:
      - "http"
      - "locadora-gateway:80"
    depends_on:
      - gateway
