server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Se a URL não apontar para um arquivo existente, redireciona para index.html 
    location / {
        try_files $uri $uri/ /index.html;
    }


    # O Nginx está atuando como proxy reverso, escondendo a porta do backend
    # location /api/ {

    #     # Corta o /api/ do começo da URL
    #     rewrite ^/api/(.*)$ /$1 break;

    #     # 'backend' é o nome do serviço no docker-compose
    #     proxy_pass http://locadora-backend:8080/;
        
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }
}