CREATE TABLE renters(
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	telephone VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	cpf VARCHAR(255) UNIQUE NOT NULL
)